# Supabase configuration file

[api]
enabled = true
port = 54321
schemas = ["public", "core", "gen", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
buckets = [
  { name = "documents", public = false },
  { name = "uploads", public = false }
]

[edge_functions]
enabled = true
port = 54324

[analytics]
enabled = false