apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: activcv-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/PROJECT_ID/activcv-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: activcv-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containerConcurrency: 100
      containers:
      - image: gcr.io/PROJECT_ID/activcv-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          value: "https://activcv-backend-PROJECT_ID.a.run.app"
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
