apiVersion: apps/v1
kind: Deployment
metadata:
  name: activcv-backend
  labels:
    app: activcv-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activcv-backend
  template:
    metadata:
      labels:
        app: activcv-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/activcv-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activcv-frontend
  labels:
    app: activcv-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activcv-frontend
  template:
    metadata:
      labels:
        app: activcv-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/activcv-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          value: "http://activcv-backend-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: activcv-backend-service
spec:
  selector:
    app: activcv-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: activcv-frontend-service
spec:
  selector:
    app: activcv-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
