global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # FastAPI application metrics
  - job_name: 'ai-cv-agent-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

  # Job queue metrics
  - job_name: 'job-queue-metrics'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/api/v1/metrics/jobs'
    scrape_interval: 60s

  # Document vault metrics
  - job_name: 'document-vault-metrics'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/api/v1/metrics/documents'
    scrape_interval: 300s