# fly.toml app configuration file generated for activ-cv-agent
app = "activ-cv-agent"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[env]
  PORT = "8000"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
